# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o_Z7HaLvhYfTAe2cWWhDzhNXpzZKX7DI
"""

import mpmath as mp
from mpmath import *
import math
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

gamma_res = 1/(2*(math.gamma(0.25)))

gamma_np = np.frompyfunc(mp.gammainc, 3, 1)

x1 = np.arange(-10,0,0.01)

y1 = gamma_res*gamma_np(0.25 ,x1**4,inf)

x = np.arange(0,10,0.01)

y = (0.5) + gamma_res*gamma_np(0.25 ,0 , x**4)

fig, ax = plt.subplots()

ax.plot(x1,y1,label = r"$\frac{1}{2\Gamma(\frac{1}{4})}\Gamma(\frac{1}{4},x^{4})$")
ax.plot(x,y,label = r"$\frac{1}{2} + \frac{1}{2\Gamma(\frac{1}{4})}\gamma(\frac{1}{4},x^{4})$")
plt.legend()
ax.grid()
plt.xlabel('x - axis')
plt.show