# -*- coding: utf-8 -*-
"""Assignment6.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1Gn1K9lMkCa0aocDqX_VzjeJC9ErPQs
"""

import random as rd
import math
from scipy.stats import uniform

count = 0
len = 100000
R = uniform.rvs(0.1,10) # Radius of circle
x = uniform.rvs(0,2*math.pi) # Angle subtended by sector

# Checking whether point lies within sector
for i in range(len):
  p = rd.random()
  q = p * 2 * math.pi # angle subtended by point with positive X-axis
  r = R * math.sqrt(p)     # polar distance of point
  if ( q <= x and r <= R):
          count += 1

prob = count / len

print("Simulated probability = ", prob)
print("Theorotical probability = ", x/(2*math.pi))