# -*- coding: utf-8 -*-
"""assignment8pdfcdf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14XKazsMKDrezTZu7Om3ZBHdT5qVmGL1r
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
from scipy import integrate
import random

def pdf(x):
  if x == 0:
    y=2/3 +0*x
  elif x > 0 and x < 1 :
    y=x**2
  elif x>=1:
    y=0
  return y
  
def cdf(x):
  if x >= 0 and x <= 1 :
    y=2/3+x**3/3
  elif x>=1:
    y=1
  return y


print(f'theoretrical P(w>0)=',1-cdf(0))

vpdf=np.vectorize(pdf)
x1=np.linspace(0,2)
y1=vpdf(x1)
plt.plot(x1,y1)
plt.xlabel("W")
plt.ylabel("PDF")
plt.title("PDF of W")
plt.grid()
plt.show()

vcdf=np.vectorize(cdf)
x2=np.linspace(0,2)
y2=vcdf(x2)

plt.plot(x2,y2)
plt.xlabel("W")
plt.ylabel("CDF")
plt.title("CDF of W")
plt.grid()
plt.show()