# -*- coding: utf-8 -*-
"""assignment8sim.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVO5V_aqIlheERODPtQWjXwpneBYFZZ0
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats
import random
num_sim=10000000

w=0
count=0
for i in range(num_sim):
   y=random.uniform(0,1)
   x=random.uniform(0,1)
   if x**2>=y :
      w=x
      count+=1
   elif x**2<y :
      w=0
prob_wgreat0=count/num_sim
prob_w0=1-prob_wgreat0
print(f'P(W>0)=',prob_wgreat0)
print(f'P(W=0)=',prob_w0)