# -*- coding: utf-8 -*-
"""Assignment_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kh0mz2Hx50AX67ArF_Ip9J4jNjDTLPPp
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

#For plotting the PDF of V
#Setting the corresponding x and y co-ordinates
#Region 1 of PDF
x_1 = np.arange(-3,-1,0.01)
y_1 = x_1*0
#Region 2 of PDF 
x_2 = np.arange(-1,0,0.01)
y_2 = 1 + x_2
#Region 3 of PDF
x_3 = np.arange(0,1,0.01)
y_3 = 1 -x_3
#Region 4 of PDF
x_4 = np.arange(1,3,0.01)
y_4 = x_4*0

#Plotting the points
plt.plot(x_1,y_1,'b')
plt.plot(x_2,y_2,'b')
plt.plot(x_3,y_3,'b')
plt.plot(x_4,y_4,'b')
plt.xlabel('Random Variable,V')
plt.ylabel('$f_V(v)$')

plt.grid()
plt.show()

#For plotting the CDF of V
#Setting the corresponding x and y co-ordinates
#Region 1 of CDF
x_1 = np.arange(-3,-1,0.01)
y_1 = x_1*0
#Region 2 of CDF
x_2 = np.arange(-1,0,0.01)
y_2 = (x_2**2 + 2*x_2 +1)/2
#Region 3 of CDF
x_3 = np.arange(0,1,0.01)
y_3 = (1+ 2*x_3 -x_3**2)/2
#Region 4 of CDF
x_4 = np.arange(1,3,0.01)
y_4 = x_4**0

#Plotting the points
plt.plot(x_1,y_1,'b')
plt.plot(x_2,y_2,'b')
plt.plot(x_3,y_3,'b')
plt.plot(x_4,y_4,'b')
plt.xlabel('Random Variable,V')
plt.ylabel('$F_V(v)$')

plt.grid()
plt.show()